# Generated by Django 4.0.2 on 2024-01-12 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('icon', models.CharField(max_length=500, verbose_name='Icono FontAwesome')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dashboard/%Y/%m/%d', verbose_name='Logo')),
                ('author', models.CharField(max_length=120, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'permissions': (('view_dashboard', 'Can view Dashboard'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('hour', models.TimeField(default=datetime.datetime.now)),
                ('remote_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('login_attempt', models.CharField(choices=[('success', 'Éxito'), ('failed', 'Fallido')], default='success', max_length=20)),
                ('http_user_agent', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Acceso de Usuario',
                'verbose_name_plural': 'Acceso de Usuarios',
                'permissions': (('view_user_access', 'Can view Acceso de Usuario'), ('delete_user_access', 'Can delete Acceso de Usuario')),
                'default_permissions': (),
            },
        ),
    ]
