# Generated by Django 4.0.2 on 2024-01-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del servicio')),
                ('duracion', models.CharField(max_length=13, verbose_name='duracion en días o meses')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio del servicio')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='precio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='Nombre',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
