# Generated by Django 4.0.2 on 2024-01-23 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_plan_remove_servicio_duracion_remove_servicio_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='nombre',
        ),
        migrations.AddField(
            model_name='plan',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pos.servicio', verbose_name='Servicio'),
            preserve_default=False,
        ),
    ]
