# Generated by Django 4.0.2 on 2024-01-24 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_rename_nombre_servicio_nombre_remove_plan_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('ci', models.CharField(max_length=13, unique=True, verbose_name='Número de cédula de identidad')),
                ('genero', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=50, verbose_name='Genero')),
                ('celular', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nro de Celular')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('fecha_nacimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='duracion',
            field=models.CharField(max_length=13, verbose_name='duracion en días '),
        ),
    ]
