# Generated by Django 4.0.2 on 2024-01-28 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_inscripcion_inscripciondetalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='employee',
            new_name='empleado',
        ),
        migrations.RemoveField(
            model_name='inscripciondetalle',
            name='servicio',
        ),
    ]
